/** Generate `docs/token-inventory.md` so the doc can never drift from the document. */

import { ext, walk } from './tokens.mjs'
import { COMPONENTS } from './sass-targets.mjs'
import { layerOf } from './validate.mjs'
import { MAP_ORDER } from './emit-scss.mjs'

export function emitInventory(doc, { version }) {
  const byLayer = { primitive: [], semantic: [], component: [] }
  const byMap = new Map()

  for (const [path, token] of walk(doc.tree)) {
    byLayer[layerOf(path)].push(path)
    const map = ext(token).sassMap
    if (map) byMap.set(map, (byMap.get(map) ?? 0) + 1)
  }

  const lines = [
    '# Token inventory',
    '',
    `> Generated by \`bstokens build\` from Bootstrap v${version}. Do not edit.`,
    '',
    '| layer | tokens |',
    '| --- | ---: |',
    `| primitive | ${byLayer.primitive.length} |`,
    `| semantic | ${byLayer.semantic.length} |`,
    `| component | ${byLayer.component.length} |`,
    `| **total** | **${doc.tokens.size}** |`,
    '',
    'Primitive counts include the generated colour scale (16 hues × 13 stops).',
    '',
    '## Global maps',
    '',
    '| Sass map | tokens |',
    '| --- | ---: |'
  ]

  for (const name of MAP_ORDER) {
    if (byMap.has(name)) lines.push(`| \`${name}\` | ${byMap.get(name)} |`)
  }

  lines.push('', '## Component maps', '', '| component | Sass map | selector | tokens |', '| --- | --- | --- | ---: |')

  for (const component of [...COMPONENTS].sort((a, b) => a.name.localeCompare(b.name))) {
    const count = byMap.get(component.sassMap) ?? 0
    const selector = component.selector.replace(/\|/g, '\\|')
    const variant = component.variantOf ? ` <sup>variant of \`${component.variantOf}\`</sup>` : ''
    lines.push(`| \`${component.name}\`${variant} | \`${component.sassMap}\` | \`${selector}\` | ${count} |`)
  }

  return `${lines.join('\n')}\n`
}
