/**
 * `bstokens init` — turn a theme into a project that compiles.
 *
 * The export dialog hands you a `custom.scss` and four numbered steps. That is fine, but the
 * steps are where people fall off: the wrong Bootstrap version, no Sass, the stylesheet
 * linked but never compiled. This writes the whole thing — the entry stylesheet, a
 * package.json with the right dependencies and scripts, and a page that uses it — so the
 * only remaining step is `npm install`.
 */

import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

import { loadTree, loadOptions } from '../lib/load-fs.mjs'
import { withOverrides, themeScss, changedKeysOf, mapsTouched } from '../lib/overrides.mjs'
import { changedOptions } from '../lib/config-surface.mjs'
import { tokensDir } from '../lib/config.mjs'
import { sourceVersion } from './build.mjs'

/*
 * Bootstrap 6 is not on npm — the registry has nothing above 5.x — so a semver range would
 * fail `npm install` in the very file meant to prove this works. The branch is the only way
 * to get v6 today, and it installs cleanly: twbs/bootstrap ships `scss/**` in its `files`
 * and defines no prepare script, so there is nothing to build. Override with --bootstrap
 * once a release exists.
 */
const BOOTSTRAP_DEFAULT = 'github:twbs/bootstrap#v6-dev'

/*
 * The scaffold depends on this package so `npm run verify` works without a global install.
 * Pinned to the repository for the same reason Bootstrap is: there is no published release
 * yet, and a semver range that resolves to nothing fails at `npm install` — in the very
 * feature meant to prove the export works.
 */
const BOOTSTRAP_TOKENS_DEFAULT = 'github:julien-deramond/bootstrap-tokens'

function readTheme(path) {
  if (!path) return { overrides: {}, options: {} }

  const parsed = JSON.parse(readFileSync(path, 'utf8'))
  if (!parsed || typeof parsed.overrides !== 'object') {
    throw new Error(`${path} is not a theme file — expected an "overrides" object.`)
  }
  return { overrides: parsed.overrides, options: parsed.options ?? {} }
}

const INDEX_HTML = (name) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${name}</title>
    <link href="css/app.css" rel="stylesheet" />
  </head>
  <body class="p-4">
    <h1>${name}</h1>
    <p class="lead">Your theme is compiled into <code>css/app.css</code>.</p>

    <div class="d-flex flex-wrap gap-2 my-4">
      <button type="button" class="btn btn-solid theme-primary">Primary</button>
      <button type="button" class="btn btn-outline theme-primary">Outline</button>
      <button type="button" class="btn btn-solid theme-success">Success</button>
    </div>

    <div class="alert theme-primary" role="alert">
      <p class="m-0">Edit <code>scss/custom.scss</code> and run <code>npm run watch</code>.</p>
    </div>
  </body>
</html>
`

const README = (name) => `# ${name}

A Bootstrap v6 theme, generated by [bootstrap-tokens](https://github.com/julien-deramond/bootstrap-tokens).

\`\`\`bash
npm install
npm run watch     # rebuild css/app.css as you edit
npm run build     # one compressed build
npm run verify    # check the theme compiles to the values you previewed
\`\`\`

Then open \`index.html\`.

\`npm run verify\` is the one worth knowing about. It compiles this theme against the Bootstrap
you actually installed and compares every custom property it produces with what the chooser
showed you. "It looked right in the tool" and "it compiles to this" are different claims, and
only the second one survives a dependency bump.

## What is where

| Path | What it is |
| --- | --- |
| \`scss/custom.scss\` | Your theme. It configures Bootstrap through \`@use … with ()\`, so only the values you changed are here. |
| \`theme.json\` | The same theme in portable form. Load it back into the chooser to keep editing. |
| \`css/app.css\` | The compiled stylesheet. Link this instead of Bootstrap's own. |

Everything not listed in \`custom.scss\` comes from Bootstrap's defaults, so upgrading is a
matter of bumping the dependency.

## About the Bootstrap dependency

Bootstrap 6 is not published to npm yet, so \`package.json\` points at the \`v6-dev\` branch.
Once there is a release, swap it for a version range.
`

export async function init({ flags, positional }) {
  const target = resolve(positional[0] ?? flags.out ?? 'bootstrap-theme')
  const name = flags.name ?? target.split(/[\\/\\\\]/).pop()

  if (existsSync(target) && readdirSync(target).length > 0 && !flags.force) {
    throw new Error(`${target} already exists and is not empty. Pass --force to write into it anyway.`)
  }

  const { overrides, options } = readTheme(flags.theme)
  const { tree } = loadTree(tokensDir)
  const doc = withOverrides(tree, overrides)
  const baseOptions = loadOptions(tokensDir)

  const scss = themeScss(doc, overrides, {
    version: sourceVersion(),
    importPath: '../node_modules/bootstrap/scss/bootstrap',
    options: changedOptions(baseOptions, { ...baseOptions, ...options })
  })

  const files = {
    'scss/custom.scss': scss,
    'index.html': INDEX_HTML(name),
    'README.md': README(name),
    '.gitignore': 'node_modules/\ncss/\n',
    // The name is carried through so reopening the theme, or verifying it, still calls it
    // what you called it rather than "theme.json".
    'theme.json': `${JSON.stringify(
      { format: 'bootstrap-tokens-theme@1', name, bootstrap: sourceVersion(), overrides, options },
      null,
      2
    )}\n`,
    'package.json': `${JSON.stringify(
      {
        name: name.toLowerCase().replace(/[^a-z0-9-]+/g, '-'),
        private: true,
        type: 'module',
        scripts: {
          build: 'sass --style=compressed --no-source-map scss/custom.scss css/app.css',
          watch: 'sass --watch scss/custom.scss css/app.css',
          /*
           * The theme compiles here, against your own installed Bootstrap, and every value
           * is compared with what the chooser previewed. Worth having in the project rather
           * than only in this repository: the version you install is the one that matters,
           * and "it looked right in the tool" is not the same claim as "it compiles to this".
           */
          verify: 'bstokens verify --theme theme.json --src node_modules/bootstrap'
        },
        dependencies: { bootstrap: flags.bootstrap ?? BOOTSTRAP_DEFAULT },
        devDependencies: { sass: '^1.93.0', 'bootstrap-tokens': BOOTSTRAP_TOKENS_DEFAULT }
      },
      null,
      2
    )}\n`
  }

  for (const [relative, content] of Object.entries(files)) {
    const path = join(target, relative)
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
    console.log(`  ${relative}`)
  }

  const touched = mapsTouched(doc, overrides).size
  const keys = [...changedKeysOf(doc, overrides).values()].reduce((sum, set) => sum + set.size, 0)

  console.log(
    `\nWrote a project to ${target}` +
      (flags.theme
        ? ` carrying ${keys} map key${keys === 1 ? '' : 's'} across ${touched} Sass map${touched === 1 ? '' : 's'}.`
        : '.')
  )
  console.log(`\n  cd ${target}\n  npm install\n  npm run watch`)

  return 0
}
